//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by poker.rc
//
#define IDD_STATS                       101
#define IDI_ICON1                       102
#define IDI_ICON2                       103
#define IDD_ABOUT                       104
#define IDD_HELPCONTENTS                105
#define IDI_POINTER                     107
#define IDD_HELPSCORING                 108
#define IDD_POKERPAY                    109
#define IDD_HELPPAYTABLE                110
#define IDD_HELPKEYBOARD                111
#define IDPAY56                         200
#define IDPAY57                         201
#define IDPAY58                         202
#define IDPAY69                         203
#define IDOK2                           204
#define IDPAY70                         205
#define IDPAYTENSORBETTER               206
#define IDC_RESET                       1001
#define IDC_HELPSCORING                 1005
#define IDC_HELPKEYBOARD                1007
#define IDC_HELPPAYTABLE                1008
#define IDC_PAYROYALFLUSH               1018
#define IDC_PAYSTRAIGHTFLUSH            1019
#define IDC_PAYFOUROFAKIND              1020
#define IDC_PAYFULLHOUSE                1021
#define IDC_PAYFLUSH                    1022
#define IDC_PAYSTRAIGHT                 1023
#define IDC_PAYTHREEOFAKIND             1024
#define IDC_PAYTWOPAIR                  1025
#define IDC_PAYJACKSORBETTER            1026
#define IDC_PAYTENSORBETTER             1027
#define IDC_PAYROYALFLUSH5              1029
#define IDCHECKOK                       1031
#define IDPAYHELP                       1032
#define HAND_PLAYED                     2000
#define HAND_SCORED                     2001
#define HAND_AVERAGE                    2002
#define HAND_BET                        2003
#define CREDITS_CURRENT                 3001
#define CREDITS_DEPOSITED               3002
#define CREDITS_WITHDRAWN               3003
#define CREDITS_TOTAL                   3004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        250
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
