//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by whizzy.rc
//
#define IDD_WHIZZY                      101
#define IDC_BUTTON_ENABLE               1000
#define IDC_SCROLLBAR_TEMPERATURE       1001
#define IDC_EDIT_FAHRENHEIT             1002
#define IDC_EDIT_CELSIUS                1003
#define IDC_RADIO_ENGLISH               1004
#define IDC_RADIO_FRENCH                1005
#define IDC_RADIO_SPANISH               1006
#define IDC_CHECK_BIG                   1008
#define IDC_CHECK_GREEN                 1009
#define IDC_BOX_TEMPERATURE             1010
#define IDC_TEXT_FAHRENHEIT             1011
#define IDC_TEXT_CELSIUS                1012
#define IDC_BOX_LANGUAGE                1013
#define IDC_BOX_CREATURE                1014
#define IDC_STATIC_CREATURE             1015
#define IDC_LIST1                       1016
#define IDC_LIST2                       1017
#define IDC_BUTTONRIGHT                 1018
#define IDC_BUTTONLEFT                  1019
#define IDC_COMBO1                      1020
#define IDC_STATIC_WISDOM               1021
#define IDC_BOX_EMPLOYEES               1022
#define IDC_BOX_SURVEY                  1023
#define IDC_TEXT_AVAILABLE              1024
#define IDC_TEXT_UNAVAILABLE            1025
#define IDC_BUTTON_DEJAVU               1026

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
