//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by fxplorer.rc
//
#define IDD_FXPLORER_DIALOG             101
#define IDC_VER1                        1001
#define IDC_VER2                        1002
#define IDC_VER3                        1003
#define IDC_VER4                        1004
#define IDC_VER5                        1005
#define IDC_EXPLORER1                   1006
#define IDC_PROGRESS1                   1007
#define IDC_EDIT1                       1010
#define IDC_URLLABEL                    1013
#define IDM_EXIT                        30001
#define IDM_NEW                         30002
#define IDM_GO                          30002
#define IDM_OPEN                        30003
#define IDM_STOP                        30003
#define IDM_SAVE                        30004
#define IDM_SAVEAS                      30005
#define IDM_PRINT                       30006
#define IDM_PRINTSETUP                  30007
#define IDM_UNDO                        30008
#define IDM_CUT                         30009
#define IDM_COPY                        30010
#define IDM_PASTE                       30011
#define IDM_HELPCONTENTS                30012
#define IDM_HELPSEARCH                  30013
#define IDM_HELPHELP                    30014
#define IDM_ABOUT                       30015
#define IDM_BACK                        30017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         30018
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
